import pathlib

p = pathlib.Path("tests/test_phase4_api.py")
t = p.read_text(encoding="utf-8")
if "DaemonProjectListQueryRouteTests" in t:
    print("already added")
    raise SystemExit(0)

lines = []
lines.append("")
lines.append("")
lines.append("class DaemonProjectListQueryRouteTests(unittest.TestCase):")
lines.append('    """Regression for query-parameter parsing on /v1/tasks and /v1/projects."""')
lines.append("")
lines.append("    @staticmethod")
lines.append("    def _free_port():")
lines.append("        import socket")
lines.append("        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)")
lines.append('        sock.bind(("127.0.0.1", 0))')
lines.append("        port = sock.getsockname()[1]")
lines.append("        sock.close()")
lines.append("        return port")
lines.append("")
lines.append("    def setUp(self):")
lines.append("        from relay.daemon import RelayDaemon")
lines.append("        from relay.config import Config")
lines.append("        self.temp = tempfile.TemporaryDirectory()")
lines.append('        self.home = Path(self.temp.name) / "home"')
lines.append("        self.config = Config(self.home)")
lines.append("        self.config.init()")
lines.append('        self.config.set("daemon_port", self._free_port())')
lines.append("        self.daemon = RelayDaemon(self.config)")
lines.append("        self.thread = threading.Thread(target=self.daemon.serve, daemon=True)")
lines.append("        self.thread.start()")
lines.append("        from relay.rpc import RPCClient")
lines.append("        self.client = RPCClient(self.config)")
lines.append("        self.assertTrue(self.client.wait_until_healthy(5.0))")
lines.append("")
lines.append("    def tearDown(self):")
lines.append("        if self.thread.is_alive():")
lines.append("            try:")
lines.append('                self.client.request("POST", "/shutdown")')
lines.append("            except RelayError:")
lines.append("                pass")
lines.append("            self.thread.join(timeout=5)")
lines.append("        self.temp.cleanup()")
lines.append("")
lines.append("    def _seed(self, count_tasks=3, count_projects=2):")
lines.append("        task_ids = []")
lines.append("        for i in range(count_tasks):")
lines.append("            created = self.client.request(")
lines.append('                "POST",')
lines.append('                "/v1/tasks",')
lines.append("                {")
lines.append('                    "name": f"SpecTask-{i}",')
lines.append('                    "instructions": f"work {i}",')
lines.append('                    "worker": "auto",')
lines.append('                    "profile": "web-research",')
lines.append('                    "result_format": "json",')
lines.append("                },")
lines.append("            )")
lines.append('            task_ids.append(created["task"]["task_id"])')
lines.append("        project_ids = []")
lines.append("        for i in range(count_projects):")
lines.append("            project = self.client.request(")
lines.append('                "POST",')
lines.append('                "/v1/projects",')
lines.append("                {")
lines.append('                    "name": f"Project-{i}",')
lines.append('                    "nodes": [{"node_id": "n1", "task_id": task_ids[0]}]')
lines.append('                    if task_ids else [{"node_id": "n1", "task_id": "noop"}],')
lines.append('                    "connections": [],')
lines.append('                    "output_selection": [],')
lines.append("                },")
lines.append("            )")
lines.append('            project_ids.append(project["project"]["project_id"])')
lines.append("")
lines.append("    def test_task_list_with_name_filter_returns_matching(self):")
lines.append("        self._seed()")
lines.append('        named = self.client.request("GET", "/v1/tasks?name=SpecTask-1")')
lines.append('        self.assertEqual([t["name"] for t in named["tasks"]], ["SpecTask-1"])')
lines.append('        empty = self.client.request("GET", "/v1/tasks?name=NoSuchTask")')
lines.append('        self.assertEqual(empty["tasks"], [])')
lines.append("")
lines.append("    def test_task_list_with_limit_caps_results(self):")
lines.append("        self._seed(count_tasks=4)")
lines.append('        limited = self.client.request("GET", "/v1/tasks?limit=2")')
lines.append('        self.assertEqual(len(limited["tasks"]), 2)')
lines.append("")
lines.append("    def test_task_list_with_invalid_limit_returns_400(self):")
lines.append("        with self.assertRaises(RelayError) as ctx:")
lines.append('            self.client.request("GET", "/v1/tasks?limit=oops")')
lines.append('        self.assertEqual(ctx.exception.code, "INVALID_REQUEST")')
lines.append("")
lines.append("    def test_project_list_with_name_filter_returns_matching(self):")
lines.append("        self._seed()")
lines.append('        named = self.client.request("GET", "/v1/projects?name=Project-0")')
lines.append('        self.assertEqual([p["name"] for p in named["projects"]], ["Project-0"])')
lines.append('        empty = self.client.request("GET", "/v1/projects?name=NoSuchProject")')
lines.append('        self.assertEqual(empty["projects"], [])')
lines.append("")
lines.append("    def test_project_list_with_limit_caps_results(self):")
lines.append("        self._seed(count_projects=4)")
lines.append('        limited = self.client.request("GET", "/v1/projects?limit=2")')
lines.append('        self.assertEqual(len(limited["projects"]), 2)')
lines.append("")
lines.append("    def test_project_runs_with_limit_caps_results(self):")
lines.append("        from relay.models import TaskSpec")
lines.append('        ta = self.engine.create_task(TaskSpec(name="TA", instructions="a"))')
lines.append("        project = self.engine.project_service.create_project(")
lines.append("            {")
lines.append('                "name": "P",')
lines.append('                "nodes": [{"node_id": "a", "task_id": ta["task_id"]}],')
lines.append('                "connections": [],')
lines.append('                "output_selection": [],')
lines.append("            }")
lines.append("        )")
lines.append("        for _ in range(3):")
lines.append('            self.client.request("POST", f"/v1/projects/{project[\'project_id\']}/run", {})')
lines.append("        limited = self.client.request(")
lines.append('            "GET", f"/v1/projects/{project[\'project_id\']}/runs?limit=1"')
lines.append("        )")
lines.append('        self.assertEqual(len(limited["project_runs"]), 1)')
lines.append("")
lines.append("")
lines.append('if __name__ == "__main__":')
lines.append("    unittest.main()")
lines.append("")

addition = "\n".join(lines)
marker = 'if __name__ == "__main__":\n    unittest.main()\n'
t = t.replace(marker, addition, 1)
p.write_text(t, encoding="utf-8")
print("appended")
