import pathlib
p = pathlib.Path("tests/test_phase5_cli.py")
t = p.read_text(encoding="utf-8")
if "DaemonRoutineListQueryRouteTests" in t:
    print("already added")
    raise SystemExit(0)

lines = []
lines.append("")
lines.append("")
lines.append("class DaemonRoutineListQueryRouteTests(unittest.TestCase):")
lines.append('    """Regression for query-parameter parsing on /v1/routines."""')
lines.append("")
lines.append("    @staticmethod")
lines.append("    def _free_port():")
lines.append("        import socket")
lines.append("        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)")
lines.append('        sock.bind(("127.0.0.1", 0))')
lines.append("        port = sock.getsockname()[1]")
lines.append("        sock.close()")
lines.append("        return port")
lines.append("")
lines.append("    def setUp(self):")
lines.append("        from relay.daemon import RelayDaemon")
lines.append("        from relay.config import Config")
lines.append("")
lines.append("        self.temp = tempfile.TemporaryDirectory()")
lines.append("        self.home = Path(self.temp.name) / \"home\"")
lines.append("        self.config = Config(self.home)")
lines.append("        self.config.init()")
lines.append("        self.config.set(\"daemon_port\", self._free_port())")
lines.append("        self.daemon = RelayDaemon(self.config)")
lines.append("        self.thread = threading.Thread(target=self.daemon.serve, daemon=True)")
lines.append("        self.thread.start()")
lines.append("        from relay.rpc import RPCClient")
lines.append("        self.client = RPCClient(self.config)")
lines.append("        self.assertTrue(self.client.wait_until_healthy(5.0))")
lines.append("        self.engine = self.daemon.engine")
lines.append("")
lines.append("    def tearDown(self):")
lines.append("        if self.thread.is_alive():")
lines.append("            try:")
lines.append('                self.client.request("POST", "/shutdown")')
lines.append("            except RelayError:")
lines.append("                pass")
lines.append("            self.thread.join(timeout=5)")
lines.append("        self.temp.cleanup()")
lines.append("")
lines.append("    def _seed_routine(self, name=\"Daily\"):")
lines.append('        return self.client.request("POST", "/v1/routines", {"name": name, "target_type": "task", "target_id": "demo-task", "rule": {"type": "daily", "times": [\"09:00\"], "timezone": \"UTC\"}})')
lines.append("")
lines.append("    def test_routine_list_with_name_filter_returns_matching(self):")
lines.append('        self._seed_routine("Daily-Marketing")')
lines.append('        self._seed_routine("Weekly-Dev")')
lines.append('        named = self.client.request("GET", "/v1/routines?name=Daily")')
lines.append('        self.assertEqual([r["name"] for r in named["routines"]], ["Daily-Marketing"])')
lines.append("")
lines.append("    def test_routine_list_with_limit_caps_results(self):")
lines.append("        for i in range(4):")
lines.append('            self._seed_routine(f"Routine-{i}")')
lines.append('        limited = self.client.request("GET", "/v1/routines?limit=2")')
lines.append("        self.assertEqual(len(limited[\"routines\"]), 2)")
lines.append("")
lines.append("    def test_routine_list_with_invalid_limit_returns_400(self):")
lines.append("        with self.assertRaises(RelayError) as ctx:")
lines.append('            self.client.request("GET", "/v1/routines?limit=oops")')
lines.append("        self.assertEqual(ctx.exception.code, \"INVALID_REQUEST\")")
lines.append("")
lines.append("    def test_routine_runs_with_limit_caps_results(self):")
lines.append("        routine = self._seed_routine(\"R\")")
lines.append("        rid = routine[\"routine\"][\"routine_id\"]")
lines.append("        for _ in range(3):")
lines.append("            self.engine.db.add_routine_run(")
lines.append('            {"run_id": f"rr-{_}", "routine_id": rid, "occurrence_key": f"k-{_}", "trigger_type": "manual", "status": "completed", "target_type": "task"}')
lines.append("        limited = self.client.request(")
lines.append("            \"GET\", f\"/v1/routines/{rid}/runs?limit=1\"")
lines.append("        )")
lines.append("        self.assertEqual(len(limited[\"runs\"]), 1)")
lines.append("")
lines.append("")
lines.append("if __name__ == \"__main__\":")
lines.append("    unittest.main()")
lines.append("")

addition = "\n".join(lines)
marker = 'if __name__ == "__main__":\n    unittest.main()\n'
t = t.replace(marker, addition, 1)
p.write_text(t, encoding="utf-8")
print("appended")
